# # #-----------Tuple-------------
# MyTuple = (1,2,4,5,7,4,9,8)
# # print(MyTuple[1:-2:2])
# # print(MyTuple[-5:-1])
# # print(MyTuple[1:5])
# # print(MyTuple[5:-1])
# # print(MyTuple[:5])
# # print(MyTuple[1:])
# # print("The Addtion of list is :",sum(MyTuple))
# # print("The maximum num in list is",max(MyTuple))
# # print("The minimum num in list is",min(MyTuple))
# # print(MyTuple.index(2))
# # print(MyTuple.count(1))
# # print(sorted(MyTuple,reverse = False))
# # print(sorted(MyTuple,reverse = True))
# # print(type(MyTuple))
# # print(MyTuple[::-1])
# # m1=(1,2,3,4)
# # m2=(5,6,7,8)
# # m3 = m1+m2
# # print(m3)
# # print(m1*9999)
# mylist = list(MyTuple)
# mylist[4]="ORANGE"
# print(mylist)
# MyTuple = tuple(mylist)
# print(mylist)
a = "MR_SPIDEY"
b = tuple(a)
print(b)